let mode="login",type="resume";const $=x=>document.getElementById(x),h={resume:["Create Resume","Paste your education, skills, experience, projects and certifications."],cover:["Cover Letter","Paste your profile plus the job description."],improve:["Improve Resume","Paste your current resume and target job description if available."],skills:["Match My Skills","Paste your profile and the target job description."]};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");mode=b.dataset.mode;$("authBtn").textContent=mode==="login"?"Sign in":"Create account"});
$("authBtn").onclick=async()=>{let r=await fetch("/api/auth/"+(mode==="login"?"login":"signup"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:$("email").value,password:$("password").value})}),d=await r.json();if(!r.ok)return $("authMsg").textContent=d.error;show()};
async function show(){let r=await fetch("/api/me");if(!r.ok)return;$("auth").classList.add("hidden");$("app").classList.remove("hidden");$("logout").classList.remove("hidden");refresh()}
async function refresh(){let r=await fetch("/api/me");if(!r.ok)return;let d=await r.json();$("planBadge").textContent=d.user.plan==="pro"?"Pro":"Free";$("usage").textContent=d.user.plan==="pro"?"Pro plan active":"Free usage: "+d.usage+"/5 generations"}
document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{document.querySelectorAll(".choice").forEach(x=>x.classList.remove("active"));b.classList.add("active");type=b.dataset.type;$("taskTitle").textContent=h[type][0];$("hint").textContent=h[type][1]});
$("generate").onclick=async()=>{let input=$("input").value.trim();if(input.length<30)return $("genMsg").textContent="Please provide more information."; $("genMsg").textContent="Generating...";let r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,input})}),d=await r.json();if(!r.ok)return $("genMsg").textContent=d.error;$("genMsg").textContent="";$("result").textContent=d.output;$("resultWrap").classList.remove("hidden");refresh()};
$("copy").onclick=async()=>{await navigator.clipboard.writeText($("result").textContent);$("copy").textContent="Copied";setTimeout(()=>$("copy").textContent="Copy",1000)};
$("logout").onclick=async()=>{await fetch("/api/auth/logout",{method:"POST"});location.reload()};
$("upgrade").onclick=async()=>{let r=await fetch("/api/razorpay/subscription",{method:"POST"}),d=await r.json();if(!r.ok)return $("genMsg").textContent=d.error;new Razorpay({key:d.key_id,subscription_id:d.subscription.id,name:"AI Career Boost",description:"Pro monthly plan",handler:async x=>{let v=await fetch("/api/razorpay/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(x)}),z=await v.json();$("genMsg").textContent=z.ok?"Payment verified. Pro is active.":z.error;refresh()}}).open()};show();